### ISSUE TITLE
As a user, I want to get notifications when other users favorite or repost my posts, mention my name in their posts or add me to a circle

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/circuit#101]
- notify user if they are added for the first time to someone's circle

**Comment by metalmatze** [comment]
Checkout Snackbar: http://fezvrasta.github.io/snackbarjs/

**Comment by Gjum** [comment]
Related #124

**Comment by KjellPirschel** [comment]
- [ ] notify user if their post is reposted
- [ ] notify user if their is an reply to their post 
- [ ] notify user if they are favoured
- [ ] notify user if they are added to someone's circle

**Comment by Gjum** [comment]
This conflicts with #124.
