### ISSUE TITLE
As a user I want to search posts, mentions, hashtags and circles, so that I can find what I'm looking for

### ISSUE THREAD

**Issue by Gjum** [7Pros/circuit#102]
There should be a uniform way to display search results when searching for e.g. hashtags, multiple mentions, plain text.
Requires documentation, see #118.

**Comment by metalmatze** [comment]
Searching for
- `metal` - shows all users, hashtags and posts with `metal` in it.
- `@metal` - shows all users that start with that
- `#metal` - shows all hastags that match exactly `#metal`
