### ISSUE TITLE
As a developer I want to have gulp to compile my css

### ISSUE THREAD

**Issue by metalmatze** [7Pros/circuit#113]
Compiling [bootstrap material theme](https://github.com/FezVrasta/bootstrap-material-design/tree/master/sass) sass together with our own sass. It should create a single css file inside `circuit/static/css/`

**Comment by juanecabellob** [comment]
shouldn't be this one in the 5th sprint

**Comment by metalmatze** [comment]
We will implement most of the features for the app in the next sprint. But I want to bootstrap gulp in this sprint, so that we can start with it in the next sprint right away.
