### ISSUE TITLE
As a developer, I want to use gulp.

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/circuit#138]
After doing the new steps in order to get the project running, the `README` must be updated so we can know what dependencies are to be expected when trying to run `gulp`. 

Following dependencies are missing:
- [x] `npm install gulp-less gulp-sourcemaps gulp-concat`

**Comment by metalmatze** [comment]
You're right, I forgot to mention that you need to run `npm install` this will install all necessary packages for gulp.

**Comment by metalmatze** [comment]
I've added the part with `npm install` in this commit https://github.com/7Pros/circuit/commit/2fb8416e2f166026b58763c79ebf1f775cca58a8.
Sorry that I missed that.
