### ISSUE TITLE
Unable to upload a new profile picture

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/circuit#163]

**Comment by juanecabellob** [comment]
As I'm not able to change the labels of the issues, this is a "question" labeled issue

**Comment by metalmatze** [comment]
We use https://de.gravatar.com/ since we don't want to recreate this.

**Comment by juanecabellob** [comment]
that's the point, we should be able to make this optional for the users. gravatar should only be the default profile picture.

**Comment by juanecabellob** [comment]
don't you think? i mean that's what are the social networks for.

**Comment by juanecabellob** [comment]
they enable the user to personalize his profile

**Comment by Gjum** [comment]
gravatar is a service to upload your own profile picture and use it among multiple services, e.g. github and circuit. You can upload your own image there already.

**Comment by juanecabellob** [comment]
well then we have to document this

**Comment by juanecabellob** [comment]
this can be closed now

**Comment by Gjum** [comment]
Then do it ;)
