### ISSUE TITLE
Change delete and edit button for a "···" button just as twitter does it

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/circuit#164]

**Comment by juanecabellob** [comment]
As I'm not able to change the labels of the issues, this is a "question" labeled issue

**Comment by nrigheriu** [comment]
what are some reasons to do it? i think it looks good like this

**Comment by metalmatze** [comment]
This is completely obsolete.

**Comment by juanecabellob** [comment]
we have to much buttons..

**Comment by juanecabellob** [comment]
it would help to differentiate the button functions, the one's we are showing are "the most used buttons" and the ones that perform an interaction with the post.. showing them all implies that everything is kinda the same and the edit and delete button are not performing user-interaction but exactly the opposite..i mean it's not bad if we leave like that, but I think this way is better to display our buttons
