### ISSUE TITLE
Star not shown on post detail view

### ISSUE THREAD

**Issue by Gjum** [7Pros/circuit#169]
When I star a post and then click on its date to get to its detail page, the star is not shown anymore. It shows as not starred instead.

**Comment by juanecabellob** [comment]
can you please assign this to me?

**Comment by juanecabellob** [comment]
I've tried to replicate the bug but I couldn't make it. It works for me.

**Comment by Gjum** [comment]
Seems to be fixed again somehow while merging. I suspect it was a missing entry in the template `context`.
