### ISSUE TITLE
As a user, I want to see the number of times that my post has been reposted

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/circuit#187]
As we are planning to implement it with the favorites posts, it should be the same way for the reposts

**Comment by juanecabellob** [comment]
Related #179

**Comment by Gjum** [comment]
@juanecabellob are you already working on this?

**Comment by juanecabellob** [comment]
yes, i'm working on this but i will add this to the favorite posts branch because it is related

**Comment by Gjum** [comment]
ok, nice.
