### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by metalmatze** [7Pros/circuit#62]

**Comment by metalmatze** [comment]
Write CIT for GitLab CI

**Comment by Gjum** [comment]
@juanecabellob wanted to check out Amazon's services for this.

**Comment by juanecabellob** [comment]
What is this all about?

**Comment by juanecabellob** [comment]
something like travis.ci?

**Comment by metalmatze** [comment]
It was partially. But I was created to remember to setup CI like @Gjum did.
