### ISSUE TITLE
As a user, I want to write a post, so that everyone can read it.

### ISSUE THREAD

**Issue by metalmatze** [7Pros/circuit#65]

**Comment by metalmatze** [comment]
1. Form to write a post on top of all posts in user profile
2. Limit the post's chars to 256, and show remaining chars in the input form
3. Save to db
4. Refresh to current page once posted.

**Comment by Gjum** [comment]
This should be worked on quickly as #66, #67, #68, and #69 depend on this.

**Comment by Gjum** [comment]
Also, the title of this issue is misleading. Not everyone should be able to read any post, only users that are part of the circle to which the author published the post.

For now this is ok, as there are no circles yet. Should be thought of later though.

**Comment by metalmatze** [comment]
Yes, we can only implement that everyone can read it for now. Visibility will come later.

**Comment by metalmatze** [comment]
The other issues don't really depend on this feature, since you can simply add a post in the db or admin section. To test your feature.

**Comment by Gjum** [comment]
Ah, completely forgot about the admin section. :D
