### ISSUE TITLE
As a user, I want to edit my own posts

### ISSUE THREAD

**Issue by metalmatze** [7Pros/circuit#67]
1. Check if logged in user is author of post
2. Show edit icon, if mouse hovers post card.
3. Update post in database
4. Redirect to previous page or post.

Editing is only possible up to 5min after writing the post. If edited there must be a label that the post was edited.

**Comment by metalmatze** [comment]
_Moved to description_

**Comment by Gjum** [comment]
I'm not sure if this should really be a feature.

cc @KjellPirschel
