### ISSUE TITLE
As a user, I want to login to circuit, so that later I have access

### ISSUE THREAD

**Issue by juanecabellob** [7Pros/circuit#9]
@Iotka and @nrigheriu are responsible for this feature.
Also includes logout.

**Comment by Gjum** [comment]
TODO before merge:
- [ ] replace dead links (`href="#"`) with working ones (`href="{% url '...' %}"`)
- [ ] show/hide fields depending on if a user is logged in or not:
  - [ ] navbar: signup, login, logout, go to own profile page
  - [ ] edit own profile

**Comment by Gjum** [comment]
Related to #79
